#!/bin/bash

while [ 1 ]
do
	read state
	echo "state: $state"
	# movement
	if [[ $state == '1;' ]]
	then
		echo "go" > omx-go
	# no movement
	else
		echo "stop" > omx-go
		pid=$(pgrep omxplayer)
		kill $pid
	fi
done
