#!/bin/bash

while [ 1 ]
do
	read state
	echo "state: $state"
	# movement
	if [[ $state == '1;' ]]
	then
		echo "go" > omx-go
		echo 0 > safeguard
	# no movement
	elif [[ $state == '0;' ]]
	then
		echo 0 > safeguard
		echo "stop" > omx-go
		pid=$(pgrep omxplayer)
		kill $pid
	fi
	#cat omx-go
done
